<?php

if (isset($block) && $block->isModuleEnabled()): ?>
    <script data-cfasync="false" type="text/javascript">
        window.civchat = {
            apiKey: '<?= $block->getApi() ?>'
            <?php if ($id = $block->getUsercomUserId()): ?>
            , user_id: '<?= $id ?>'
            <?php endif ?>
        };
    </script>
    <script data-cfasync="false" type="text/javascript" src="https://<?= $block->getSubdomain() ?>/widget.js"></script>
<?php
endif ?>
